-- @block
CREATE DATABASE bank;

-- @block
USE bank;
CREATE TABLE account (
  id INT PRIMARY KEY AUTO_INCREMENT,
  account_name VARCHAR(45) UNIQUE NOT NULL,
  created_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- @block
USE bank;
CREATE TABLE transaction (
  id INT PRIMARY KEY AUTO_INCREMENT,
  account_id INT NOT NULL,
  amount DECIMAL(10, 5) NOT NULL,
  created_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (account_id) REFERENCES account(id)
);